#!/usr/bin/env node
/**
 * add-tool.mjs — Interactive wizard for adding a new tool to the documentation portal.
 *
 * Usage:
 *   node scripts/add-tool.mjs
 *   npm run add-tool
 *
 * Creates:
 *   - Entry in tools.config.json
 *   - sidebars_<tool-id>.ts
 *   - <tool-id>/intro.md (starter page)
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const siteDir = path.resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ask(rl, question, defaultValue) {
  const suffix = defaultValue ? ` [${defaultValue}]` : '';
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultValue || '');
    });
  });
}

function toCamelCase(str) {
  return str
    .replace(/^testbench-/, '')
    .replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

console.log('\n--- Add New Tool to TestBench Ecosystem ---\n');

const toolId = await ask(rl, 'Tool ID (e.g. testbench-my-tool)');

if (!toolId) {
  console.error('Tool ID is required.');
  rl.close();
  process.exit(1);
}

if (!/^[a-z][a-z0-9-]*$/.test(toolId)) {
  console.error('Tool ID must be lowercase, start with a letter, and use only a-z, 0-9, hyphens.');
  rl.close();
  process.exit(1);
}

// Check if tool already exists
const configPath = path.join(siteDir, 'tools.config.json');
const toolsConfig = fs.existsSync(configPath)
  ? JSON.parse(fs.readFileSync(configPath, 'utf-8'))
  : {};

if (toolsConfig[toolId]) {
  console.error(`Tool "${toolId}" already exists in tools.config.json.`);
  rl.close();
  process.exit(1);
}

const defaultLabel = toolId
  .split('-')
  .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
  .join(' ');

const label = await ask(rl, 'Display label', defaultLabel);
const description = await ask(rl, 'Short description');
const logo = await ask(rl, 'Logo filename in static/img/ (leave empty to skip)');

rl.close();

// ---------------------------------------------------------------------------
// 1. Update tools.config.json
// ---------------------------------------------------------------------------

const newEntry = { label };
if (description) newEntry.description = description;
if (logo) newEntry.logo = `img/${logo}`;

toolsConfig[toolId] = newEntry;

// Sort keys alphabetically for consistency
const sorted = Object.keys(toolsConfig)
  .sort()
  .reduce((acc, key) => {
    acc[key] = toolsConfig[key];
    return acc;
  }, {});

fs.writeFileSync(configPath, JSON.stringify(sorted, null, 2) + '\n');
console.log(`\n  Updated tools.config.json`);

// ---------------------------------------------------------------------------
// 2. Create sidebars file
// ---------------------------------------------------------------------------

const sidebarName = `${toCamelCase(toolId)}Sidebar`;
const sidebarPath = path.join(siteDir, `sidebars_${toolId}.ts`);

if (!fs.existsSync(sidebarPath)) {
  const sidebarContent = `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  ${sidebarName}: [
    {
      type: 'autogenerated',
      dirName: '.',
    }
  ],
};

export default sidebars;
`;
  fs.writeFileSync(sidebarPath, sidebarContent);
  console.log(`  Created sidebars_${toolId}.ts`);
} else {
  console.log(`  sidebars_${toolId}.ts already exists — skipped`);
}

// ---------------------------------------------------------------------------
// 3. Create docs directory with intro.md
// ---------------------------------------------------------------------------

const docsDir = path.join(siteDir, toolId);

if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });

  const introContent = `---
sidebar_position: 1
---

# ${label}

${description || 'Welcome to the documentation.'}
`;
  fs.writeFileSync(path.join(docsDir, 'intro.md'), introContent);
  console.log(`  Created ${toolId}/intro.md`);
} else {
  console.log(`  ${toolId}/ directory already exists — skipped`);
}

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------

console.log(`
Done! The tool "${label}" is ready.

Source docs will be synced from: ../../${toolId}/docs
Route: /${toolId}/

Next steps:
  1. Place a logo at static/img/${logo || toolId + '.svg'} (if not already there)
  2. Run "npm run sync" to pull docs from the source repo
  3. Run "npm start" to see it in the dev server
`);
